### ISSUE TITLE
Can this be used in web applications deployment

### ISSUE THREAD

**Issue by keviswang** [tokejepsen/conda-git-deployment#1]

**Comment by tokejepsen** [comment]
Hey @keviswang,

I don't know to be honest. I'm using this for deployment for VFX/Animation, but its not tied in any way. Its meant to be a universal deployment of any git repository. I don't have any experience with web applications, so I can't be of much help here.

I do have to warn you though that this is very much in development, and by no means in a final state. Hence the lack of documentation.

**Comment by tokejepsen** [comment]
Closing this issue, but with the latest state of the repository web applications deployment should definitely be possible.
